version: '3'

services:
  dataapi:
    build:
      context: ./conventioncenter
    image: bah-data:v1.0
    ports:
      - 8080:8080
    networks:
      - mcc-network
  auth:
    build:
      context: ./project-auth-api
    image: bah-auth:v1.0
    ports:
      - 8081:8081
    environment:
      API_HOST: "dataapi:8080"
    networks:
      - mcc-network
networks:
  mcc-network:
